# Based on https://github.com/kubernetes-sigs/kubespray
extends: default
ignore: |
  .git/
rules:
  indentation:
    spaces: 2
    indent-sequences: consistent
  line-length: disable
  truthy: disable
  document-start: false
  comments-indentation: false
  comments:
    min-spaces-from-content: 2
    level: error
