name: Image build

on:
  workflow_dispatch:
    inputs:
      image:
        required: true
        description: Image to build
        type: choice
        options:
          - nginx
          - postgres
      tag:
        required: true
        description: Version to tag the image

env:
  REGISTRY: ghcr.io/ai-cfia

jobs:
  build-on-release:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-build-push-container-github-registry.yml@main
    with:
      container-name: ${{ github.event.inputs.image }}
      tag: ${{ github.event.inputs.tag }}
      registry: ${{ env.REGISTRY }}
