---
name: Devops repository workflow

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  markdown-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main

  yaml-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-yaml-check.yml@main

  sh-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-sh-check.yml@main

  repo-standard:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit

  test-python:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-lint-test-python.yml@main
    secrets: inherit
